on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'  # Make sure .NET 9 SDK is installed on your runner

    # dotnet build and publish
    - name: Build Ecommerce API project
      shell: cmd
      run: dotnet build src\Ecommerce.Api\Ecommerce.Api.csproj --configuration Release

    - name: Publish Ecommerce API project
      shell: cmd
      run: dotnet publish src\Ecommerce.Api\Ecommerce.Api.csproj -c Release -o .\myapp

    - name: Deploy to IIS
      shell: cmd
      run: |
        iisreset /stop
        xcopy /s /y .\myapp\* C:\www\gh-actions-iis-demo.com\
        iisreset /start
